version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18 # Specify Node.js version 18
    commands:
      - echo Installing dependencies...
      - yarn install # Use Yarn to install dependencies

  build:
    commands:
      - echo Building the React app...
      - yarn build # Build the React app with Yarn (default is 'build' script in package.json)

artifacts:
  files:
    - "**/*" # Include all files in the directory
  base-directory: "build" # The directory containing the final build output (default for React apps)

